using SocomDiscordRichPresence.Models;

namespace SocomDiscordRichPresence
{
    public static class Globals
    {

        public static List<MapDataModel> SocomIMapList = new List<MapDataModel>()
        {
            new MapDataModel(){MapId = 0x00,MapName ="Lobby",DiscordKey="s1_lobby",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x05,MapName ="Abandonded",DiscordKey="s1_abandonded",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x09,MapName ="Bitter Jungle",DiscordKey ="s1_bitterjungle",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x01,MapName ="Blizzard",DiscordKey ="s1_blizzard",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x0A,MapName ="Blood Lake",DiscordKey ="s1_bloodlake",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x0B,MapName ="Death Trap",DiscordKey ="s1_deathtrap",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x06,MapName ="Desert Glory",DiscordKey ="s1_desertglory",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x02,MapName ="Frostfire",DiscordKey ="s1_frostfire",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x07,MapName ="Night Stalker",DiscordKey ="s1_nightstalker",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x08,MapName ="Rats Nest",DiscordKey ="s1_ratsnest",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
            new MapDataModel(){MapId = 0x0C,MapName ="The Ruins",DiscordKey ="s1_theruins",AltDiscordKey ="s1_logo",AltText = "SOCOM I"},
        };
        public static List<MapDataModel> SocomIIMapList = new List<MapDataModel>()
        {
            new MapDataModel(){MapId = 0x00,MapName ="Lobby",DiscordKey="s2_lobby",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x05,MapName ="Abandonded",DiscordKey="s2_abandoned",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x15,MapName ="Abandonded Day",DiscordKey ="s2_abandonedday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xAD,MapName ="Against the Tide",DiscordKey ="s2_againstthetide",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x09,MapName ="Bitter Jungle",DiscordKey ="s2_bitterjungle",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x1F,MapName ="Bitter Jungle Night",DiscordKey ="s2_bitterjunglenight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x01,MapName ="Blizzard",DiscordKey ="s2_blizzard",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x1A,MapName ="Blizzard Day",DiscordKey ="s2_blizzardday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x0A,MapName ="Blood Lake",DiscordKey ="s2_bloodlake",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x20,MapName ="Blood Night",DiscordKey ="s2_bloodlakenight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x48,MapName ="Crossroads",DiscordKey ="s2_crossroads",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x18,MapName ="Crossroads Night",DiscordKey ="s2_crossroadsnight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x0B,MapName ="Death Trap",DiscordKey ="s2_deathtrap",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x21,MapName ="Death Trap Night",DiscordKey ="s2_deathtrapnight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x06,MapName ="Desert Glory",DiscordKey ="s2_desertglory",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x1C,MapName ="Desert Glory Night",DiscordKey ="s2_desertglorynight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xB7,MapName ="Doomsday Delivery",DiscordKey ="s2_doomsdaydelivery",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x3E,MapName ="Enowapi",DiscordKey ="s2_enowapi",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x25,MapName ="Enowapi Night",DiscordKey ="s2_enowapinight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x47,MapName ="Fish Hook",DiscordKey ="s2_fishhook",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x17,MapName ="Fish Hook Night",DiscordKey ="s2_fishhooknight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x35,MapName ="Foxhunt",DiscordKey ="s2_foxhunt",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x23,MapName ="Foxhunt Night",DiscordKey ="s2_foxhuntnight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x02,MapName ="Frostfire",DiscordKey ="s2_frostfire",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x1B,MapName ="Frostfire Day",DiscordKey ="s2_frostfireday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xAB,MapName ="Guardian Angels",DiscordKey ="s2_guardianangels",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x52,MapName ="Guidance",DiscordKey ="s2_guidance",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x26,MapName ="Guidance Night",DiscordKey ="s2_guidancenight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xB6,MapName ="Guided Tour",DiscordKey ="s2_guidedtour",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xA3,MapName ="Hydro Electric",DiscordKey ="s2_hydroelectric",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xB5,MapName ="Lockdown",DiscordKey ="s2_lockdown",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x07,MapName ="Night Stalker",DiscordKey ="s2_nightstalker",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x1D,MapName ="Night Stalker Day",DiscordKey ="s2_nightstalkerday",AltDiscordKey ="s2_logo",AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xAC,MapName ="Protect and Serve",DiscordKey ="s2_protectandserve",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x08,MapName ="Rats Nest",DiscordKey ="s2_ratsnest",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x1E,MapName ="Rats Nest Day",DiscordKey ="s2_ratsnestday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x53,MapName ="Requiem",DiscordKey ="s2_requiem",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x27,MapName ="Requiem Day",DiscordKey ="s2_requiemday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x49,MapName ="Sandstorm",DiscordKey ="s2_sandstorm",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x59,MapName ="Sandstorm Day",DiscordKey ="s2_sandstormday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x97,MapName ="Seeding Chaos",DiscordKey ="s2_seedingchaos",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x40,MapName ="Shadow Falls",DiscordKey ="s2_shadowfalls",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x50,MapName ="Shadow Falls Day",DiscordKey ="s2_shadowfallsday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xA2,MapName ="Strangle Hold",DiscordKey ="s2_stranglehold",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x3D,MapName ="Sujo",DiscordKey ="s2_sujo",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x24,MapName ="Sujo Day",DiscordKey ="s2_sujoday",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x98,MapName ="Terminal Transaction",DiscordKey ="s2_terminaltransaction",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x34,MapName ="The Mixer",DiscordKey ="s2_themixer",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x19,MapName ="The Mixer Night",DiscordKey ="s2_themixernight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x0C,MapName ="The Ruins",DiscordKey ="s2_theruins",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x22,MapName ="The Ruins Night",DiscordKey ="s2_theruinsnight",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x99,MapName ="Upload Assault",DiscordKey ="s2_uplandassault",AltDiscordKey ="s2_logo", AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0xA1,MapName ="Urban Sweep",DiscordKey ="s2_urbansweep",AltDiscordKey ="s2_logo",AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x33,MapName ="Vigilance",DiscordKey ="s2_vigilanceday",AltDiscordKey ="s2_logo",AltText = "SOCOM II"},
            new MapDataModel(){MapId = 0x16,MapName ="Vigilance Night",DiscordKey ="s2_vigilancenight",AltDiscordKey ="s2_logo",AltText = "SOCOM II"},
        };

        public static List<MapDataModel> SOCOM3CAMapList = new List<MapDataModel>()
        {
            new MapDataModel(){MapId = 0x00,MapName ="Lobby",DiscordKey="sca_lobby",AltDiscordKey ="ca_logo",AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x64, MapName = "Harvester Suppression", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x65, MapName = "Harvester Extraction", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x66, MapName = "Harvester Escort", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x67, MapName = "Harvester Demolition", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x68, MapName = "Harvester Breach", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x69, MapName = "Harvester Convoy", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x6a, MapName = "Harvester Control", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x6b, MapName = "Harvester Small", DiscordKey = "sca_harvester", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x6c, MapName = "Crucible Control", DiscordKey = "sca_crucible", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x6d, MapName = "Crucible Convoy", DiscordKey = "sca_crucible", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x6e, MapName = "Crucible Demolition", DiscordKey = "sca_crucible", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x6f, MapName = "Crucible Escort", DiscordKey = "sca_crucible", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x71, MapName = "Crucible Small", DiscordKey = "sca_crucible", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x72, MapName = "Crucible Suppression", DiscordKey = "sca_crucible", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x73, MapName = "Killing Fields Control", DiscordKey = "sca_killingfields", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x74, MapName = "Killing Fields Convoy", DiscordKey = "sca_killingfields", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x75, MapName = "Killing Fields Demolition", DiscordKey = "sca_killingfields", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x9a, MapName = "Killing Fields Escort", DiscordKey = "sca_killingfields", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x76, MapName = "Killing Fields Small", DiscordKey = "sca_killingfields", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x77, MapName = "Killing Fields Suppression", DiscordKey = "sca_killingfields", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x78, MapName = "Citadel Breach", DiscordKey = "sca_citadel", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x79, MapName = "Citadel Control", DiscordKey = "sca_citadel", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x7a, MapName = "Citadel Demolition", DiscordKey = "sca_citadel", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x7b, MapName = "Citadel Escort", DiscordKey = "sca_citadel", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x7c, MapName = "Citadel Extraction", DiscordKey = "sca_citadel", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x7d, MapName = "Citadel Small", DiscordKey = "sca_citadel", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x7e, MapName = "Citadel Suppression", DiscordKey = "sca_citadel", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x80, MapName = "Devils Road Convoy", DiscordKey = "sca_devilsroad", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x81, MapName = "Devils Road Control", DiscordKey = "sca_devilsroad", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x82, MapName = "Devils Road Extraction", DiscordKey = "sca_devilsroad", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x83, MapName = "Devils Road Small", DiscordKey = "sca_devilsroad", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x84, MapName = "Devils Road Suppression", DiscordKey = "sca_devilsroad", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x85, MapName = "Boneyard Breach", DiscordKey = "sca_boneyard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x86, MapName = "Boneyard Extraction", DiscordKey = "sca_boneyard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x87, MapName = "Boneyard Small", DiscordKey = "sca_boneyard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x88, MapName = "Boneyard Suppression", DiscordKey = "sca_boneyard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x89, MapName = "Tidal Fury Breach", DiscordKey = "sca_tidalfury", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x8a, MapName = "Tidal Fury Control", DiscordKey = "sca_tidalfury", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x8b, MapName = "Tidal Fury Demolition", DiscordKey = "sca_tidalfury", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x8c, MapName = "Tidal Fury Extraction", DiscordKey = "sca_tidalfury", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x8d, MapName = "Tidal Fury Suppression", DiscordKey = "sca_tidalfury", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x70, MapName = "Tidal Fury Small", DiscordKey = "sca_tidalfury", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x8e, MapName = "Antenora Breach", DiscordKey = "sca_antendra", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x8f, MapName = "Antenora Control", DiscordKey = "sca_antendra", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x91, MapName = "Antenora Extraction", DiscordKey = "sca_antendra", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x92, MapName = "Antenora Small", DiscordKey = "sca_antendra", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x93, MapName = "Antenora Suppression", DiscordKey = "sca_antendra", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x90, MapName = "Storm Front Extraction", DiscordKey = "sca_stormfront", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x94, MapName = "Storm Front Control", DiscordKey = "sca_stormfront", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x95, MapName = "Storm Front Demolition", DiscordKey = "sca_stormfront", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x96, MapName = "Storm Front Suppression", DiscordKey = "sca_stormfront", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x9e, MapName = "Fault Breach", DiscordKey = "sca_fault", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x9f, MapName = "Fault Control", DiscordKey = "sca_fault", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa0, MapName = "Fault Demolition", DiscordKey = "sca_fault", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa1, MapName = "Fault Small", DiscordKey = "sca_fault", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa2, MapName = "Fault Suppression", DiscordKey = "sca_fault", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x97, MapName = "Waterworks Breach", DiscordKey = "sca_waterworks", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x98, MapName = "Waterworks Control", DiscordKey = "sca_waterworks", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x99, MapName = "Waterworks Demolition", DiscordKey = "sca_waterworks", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa8, MapName = "Waterworks Escort", DiscordKey = "sca_waterworks", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x9c, MapName = "Waterworks Small", DiscordKey = "sca_waterworks", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x9d, MapName = "Waterworks Suppression", DiscordKey = "sca_waterworks", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa3, MapName = "Blackwoods Control", DiscordKey = "sca_blackwoods", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa4, MapName = "Blackwoods Demolition", DiscordKey = "sca_blackwoods", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa5, MapName = "Blackwoods Extraction", DiscordKey = "sca_blackwoods", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa6, MapName = "Blackwoods Small", DiscordKey = "sca_blackwoods", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa7, MapName = "Blackwoods Suppression", DiscordKey = "sca_blackwoods", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x0b, MapName = "Summit Suppression Small", DiscordKey = "sca_summit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x0c, MapName = "Summit Demolition Small", DiscordKey = "sca_summit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x0d, MapName = "Summit Breach", DiscordKey = "sca_summit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x0e, MapName = "Summit Extraction", DiscordKey = "sca_summit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x0f, MapName = "Summit Control", DiscordKey = "sca_summit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x10, MapName = "Summit Suppression", DiscordKey = "sca_summit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x11, MapName = "Summit Demolition", DiscordKey = "sca_summit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x12, MapName = "Copperhead Suppression Small", DiscordKey = "sca_copperhead", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x13, MapName = "Copperhead Demolition Small", DiscordKey = "sca_copperhead", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x14, MapName = "Copperhead Suppression", DiscordKey = "sca_copperhead", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x15, MapName = "Copperhead Demolition", DiscordKey = "sca_copperhead", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x16, MapName = "Copperhead Control", DiscordKey = "sca_copperhead", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x17, MapName = "Copperhead Convoy", DiscordKey = "sca_copperhead", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x18, MapName = "Copperhead Escort", DiscordKey = "sca_copperhead", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x19, MapName = "Siphon Control", DiscordKey = "sca_siphon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x1a, MapName = "Siphon Suppression", DiscordKey = "sca_siphon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x1b, MapName = "Siphon Demolition", DiscordKey = "sca_siphon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x1c, MapName = "Siphon Extraction", DiscordKey = "sca_siphon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x1d, MapName = "Siphon Breach", DiscordKey = "sca_siphon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x1e, MapName = "Anchorage Suppression", DiscordKey = "sca_anchorage", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x1f, MapName = "Anchorage Control", DiscordKey = "sca_anchorage", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x20, MapName = "Anchorage Demolition", DiscordKey = "sca_anchorage", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x21, MapName = "Anchorage Extraction", DiscordKey = "sca_anchorage", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x22, MapName = "Anchorage Demolition Small", DiscordKey = "sca_anchorage", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x23, MapName = "Anchorage Suppression Small", DiscordKey = "sca_anchorage", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x24, MapName = "Threshold Suppression", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x25, MapName = "Threshold Control", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x26, MapName = "Threshold Convoy", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x27, MapName = "Threshold Demolition", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x28, MapName = "Threshold Extraction", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x29, MapName = "Threshold Demolition Small", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x2a, MapName = "Threshold Extraction Small", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x2b, MapName = "Threshold Suppression Small", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x2c, MapName = "Threshold Escort", DiscordKey = "sca_threshhold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x2d, MapName = "Retaliation Suppression", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x2e, MapName = "Retaliation Convoy", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x2f, MapName = "Retaliation Demolition", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x30, MapName = "Retaliation Extraction", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x31, MapName = "Retaliation Demolition Small", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x32, MapName = "Retaliation Suppression Small", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x33, MapName = "Retaliation Control", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x34, MapName = "Retaliation Escort", DiscordKey = "sca_retailiation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x35, MapName = "Bootcamp Suppression", DiscordKey = "sca_bootcamp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x36, MapName = "Bootcamp Control", DiscordKey = "sca_bootcamp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x37, MapName = "Bootcamp Convoy", DiscordKey = "sca_bootcamp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x38, MapName = "Bootcamp Demolition", DiscordKey = "sca_bootcamp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x39, MapName = "Bootcamp Extraction", DiscordKey = "sca_bootcamp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x3a, MapName = "Bootcamp Escort", DiscordKey = "sca_bootcamp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x3b, MapName = "Bootcamp Breach", DiscordKey = "sca_bootcamp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x3c, MapName = "Prowler Suppression", DiscordKey = "sca_prowler", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x3d, MapName = "Prowler Control", DiscordKey = "sca_prowler", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x3e, MapName = "Prowler Convoy", DiscordKey = "sca_prowler", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x3f, MapName = "Prowler Demolition", DiscordKey = "sca_prowler", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x40, MapName = "Echelon Suppression", DiscordKey = "sca_echelon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x41, MapName = "Echelon Demolition", DiscordKey = "sca_echelon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x42, MapName = "Echelon Control", DiscordKey = "sca_echelon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x43, MapName = "Echelon Extraction", DiscordKey = "sca_echelon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x44, MapName = "Echelon Breach", DiscordKey = "sca_echelon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x45, MapName = "Echelon Suppression Small", DiscordKey = "sca_echelon", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x46, MapName = "Aftershock Suppression", DiscordKey = "sca_aftershock", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x47, MapName = "Aftershock Demolition", DiscordKey = "sca_aftershock", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x48, MapName = "Aftershock Control", DiscordKey = "sca_aftershock", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x49, MapName = "Aftershock Extraction", DiscordKey = "sca_aftershock", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xd0, MapName = "Guidance Suppression Small", DiscordKey = "sca_guidance", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xd4, MapName = "Guidance Demolition Small", DiscordKey = "sca_guidance", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xd2, MapName = "Guidance Control Small", DiscordKey = "sca_guidance", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xdf, MapName = "FrostFire Suppression Small", DiscordKey = "sca_frostfire", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe1, MapName = "FrostFire Demolition Small", DiscordKey = "sca_frostfire", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe0, MapName = "FrostFire Control Small", DiscordKey = "sca_frostfire", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb1, MapName = "Liberation Demolition Small", DiscordKey = "sca_liberation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb2, MapName = "Liberation Control Small", DiscordKey = "sca_liberation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb3, MapName = "Liberation Escort Small", DiscordKey = "sca_liberation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb4, MapName = "Liberation Suppression Small", DiscordKey = "sca_liberation", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xd6, MapName = "FishHook Suppression Small", DiscordKey = "sca_fishhook", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xd7, MapName = "FishHook Breach Small", DiscordKey = "sca_fishhook", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xd8, MapName = "FishHook Control Small", DiscordKey = "sca_fishhook", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe3, MapName = "FishHook Extraction Small", DiscordKey = "sca_fishhook", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb6, MapName = "Desert Glory Demolition Small", DiscordKey = "sca_desertglory", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb7, MapName = "Desert Glory Control Small", DiscordKey = "sca_desertglory", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb8, MapName = "Desert Glory Extraction Small", DiscordKey = "sca_desertglory", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xb9, MapName = "Desert Glory Suppression Small", DiscordKey = "sca_desertglory", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xac, MapName = "Last Bastion Breach Small", DiscordKey = "sca_lastbastion", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xad, MapName = "Last Bastion Control Small", DiscordKey = "sca_lastbastion", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xae, MapName = "Last Bastion Extraction Small", DiscordKey = "sca_lastbastion", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xaf, MapName = "Last Bastion Suppression Small", DiscordKey = "sca_lastbastion", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xd5, MapName = "Crossroads Suppression Small", DiscordKey = "sca_crossroads", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xcb, MapName = "Crossroads Demolition Small", DiscordKey = "sca_crossroads", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xca, MapName = "Crossroads Control Small", DiscordKey = "sca_crossroads", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xbb, MapName = "Abandoned Suppression Small", DiscordKey = "sca_abandoned", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xbc, MapName = "Abandoned Demolition Small", DiscordKey = "sca_abandoned", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xbd, MapName = "Abandoned Control Small", DiscordKey = "sca_abandoned", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xdc, MapName = "Abandoned Extraction Small", DiscordKey = "sca_abandoned", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xa9, MapName = "Afterhours Suppression Small", DiscordKey = "sca_afterhours", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xaa, MapName = "Afterhours Demolition Small", DiscordKey = "sca_afterhours", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xab, MapName = "Afterhours Control Small", DiscordKey = "sca_afterhours", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xc8, MapName = "BloodLake Suppression Small", DiscordKey = "sca_bloodlake", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xc9, MapName = "BloodLake Extraction Small", DiscordKey = "sca_bloodlake", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe5, MapName = "BloodLake Escort Small", DiscordKey = "sca_bloodlake", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xdd, MapName = "BloodLake Demolition Small", DiscordKey = "sca_bloodlake", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xde, MapName = "BloodLake Control Small", DiscordKey = "sca_bloodlake", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xbe, MapName = "Blizzard Extraction Small", DiscordKey = "sca_blizzard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xbf, MapName = "Blizzard Suppression Small", DiscordKey = "sca_blizzard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xc0, MapName = "Blizzard Demolition Small", DiscordKey = "sca_blizzard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xc2, MapName = "Blizzard Control Small", DiscordKey = "sca_blizzard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x4a, MapName = "Winterblade", DiscordKey = "sca_winterblade", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x4b, MapName = "Reprisal", DiscordKey = "sca_reprisal", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x4c, MapName = "Whipsaw", DiscordKey = "sca_whipsaw", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x4d, MapName = "Broken Chains", DiscordKey = "sca_brokenchains", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x4e, MapName = "Stockpile", DiscordKey = "sca_stockpile", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x4f, MapName = "Highwire", DiscordKey = "sca_highwire", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x50, MapName = "Disruption", DiscordKey = "sca_disruption", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x51, MapName = "Bombshell", DiscordKey = "sca_bombshell", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x52, MapName = "Sea Wasp", DiscordKey = "sca_seawasp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x53, MapName = "Blind Side", DiscordKey = "sca_blindside", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x54, MapName = "Dragonfly", DiscordKey = "sca_dragonfly", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x55, MapName = "Stormcloud", DiscordKey = "sca_stormcloud", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x56, MapName = "Chokehold", DiscordKey = "sca_chokehold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x57, MapName = "Trailblazer", DiscordKey = "sca_trailblazer", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x58, MapName = "SnakePit", DiscordKey = "sca_snakepit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x59, MapName = "Frostbite", DiscordKey = "sca_frostbite", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x5a, MapName = "Shepherd", DiscordKey = "sca_shepard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x5b, MapName = "Kingfisher", DiscordKey = "sca_kingfisher", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x5c, MapName = "Winterblade IA", DiscordKey = "sca_winterblade", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x5d, MapName = "Winterblade Village", DiscordKey = "sca_winterblade", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x5e, MapName = "Reprisal", DiscordKey = "sca_reprisal", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x5f, MapName = "Whipsaw Boat Launch", DiscordKey = "sca_whipsaw", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x60, MapName = "Whipsaw Sawmill", DiscordKey = "sca_whipsaw", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x61, MapName = "Broken Chains Gulag", DiscordKey = "sca_brokenchains", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x62, MapName = "Stockpile Docks", DiscordKey = "sca_stockpile", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0x63, MapName = "Stockpile Bunker", DiscordKey = "sca_stockpile", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe6, MapName = "Highwire Village", DiscordKey = "sca_highwire", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe7, MapName = "Disruption Training", DiscordKey = "sca_disruption", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe8, MapName = "Bombshell Wharf", DiscordKey = "sca_bombshell", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xe9, MapName = "Bombshell Uranium Facility", DiscordKey = "sca_bombshell", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xea, MapName = "SeaWasp Freighter", DiscordKey = "sca_seawasp", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xeb, MapName = "Blindside Plateau", DiscordKey = "sca_blindside", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xec, MapName = "Blindside Temple", DiscordKey = "sca_blindside", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xed, MapName = "Dragonfly Helicopter Base", DiscordKey = "sca_dragonfly", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xee, MapName = "Stormcloud East Valley", DiscordKey = "sca_stormcloud", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xef, MapName = "Chokehold Brickworks", DiscordKey = "sca_chokehold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf0, MapName = "Chokehold Stadium", DiscordKey = "sca_chokehold", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf1, MapName = "Trailblazer City Streets", DiscordKey = "sca_trailblazer", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf2, MapName = "SnakePit Headquarters", DiscordKey = "sca_snakepit", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf3, MapName = "Frostbite Refinery", DiscordKey = "sca_frostbite", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf4, MapName = "Shepherd Ruins", DiscordKey = "sca_shepard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf5, MapName = "Shepherd Bridge", DiscordKey = "sca_shepard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf6, MapName = "ShepherdUnk", DiscordKey = "sca_shepard", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
            new MapDataModel(){MapId = 0xf7, MapName = "Kingfisher Bunker", DiscordKey = "sca_kingfisher", AltDiscordKey = "ca_logo", AltText = "SOCOM CA"},
        };

        public static List<GameInformationModel> GameList = new List<GameInformationModel>()
        {
            //SOCOOM II
            new GameInformationModel()
            {
                GameHash = "5C47974E99064D3BC9D07D90FEC2D1E2",
                JoinedGameAddress = 0x0064F8E8,
                JoinedGameLateAddress = 0x00694B68,
                PlayerPointerAddress = 0x00435618,
                //GameEndedAddress = 0x00694c44,
                MapListArrayAddress = 0x004527B4,
                CurrentMapIndexAddress = 0x004527D4,
                SealWinCounterAddress =0x695388,
                TerroristWinCounterAddress =0x69539C,
                // Room Name for socom II
                // 004527F8 Pointer result + 4 = pointer to game name
                RoomNameAddress = 0x004527F8,
                PlayerKillsOffset = 0x550,
                PlayerDeathsOffset = 0x556,
                MapList = SocomIIMapList,
                SealPlayerCountAddress =0x0044de68,
                TerroristPlayerCountAddress=0x0044de70,
                MaxPlayersAddress = 0x00695298,
                GameLogo = Properties.Resources.s2_GameLogo
            },
            // SOCOM 1 Back Label Disk 1 & 4
           new GameInformationModel()
           {
               GameHash = "23E3C7B5CF948896368F4003DE8C4715",
               JoinedGameAddress = 0x005a08fc,
               JoinedGameLateAddress = 0x005D6FD8,
               PlayerPointerAddress = 0x0048D548,
               //GameEndedAddress = 0x005D708C,
               MapListArrayAddress = 0x0052b9e8,
               CurrentMapIndexAddress =0x0052B9F4,
               SealWinCounterAddress = 0x005D7514,
               TerroristWinCounterAddress = 0x005D7528,
               // Room Name for SOCOM I
               // 006630C8 Pointer Results to the string. This is not populated the first time you join a game after joining a briefing room
               // Joining another one or the same one will populate it. This is a static pointer from what I've seen in my tests. It points right to the name
               RoomNameAddress = 0x00664244,
               //SOCOM I allows for the player to get negative kills which happen if the player teamkills or somehow kills themself
               //FFFFFFFF = -1
               PlayerKillsOffset = 0x48C,
               PlayerDeathsOffset = 0x494,
               MapList = SocomIMapList,
               // SOCOM 1 has the player total in 1 address so I will just use sealPlayerCountAddress for this
               SealPlayerCountAddress = 0x00588E98,
               MaxPlayersAddress = 0x005d7488,
               GameLogo = Properties.Resources.s1_GameLogo
           },
           //SOCOM 1 Black label Disk 8 (appears to be the same as the later versions?)
           new GameInformationModel()
           {
               GameHash = "DBD2D4D90EA1ED1F5A382050CE969CCF",
               JoinedGameAddress = 0x0059ecc8,
               JoinedGameLateAddress= 0x005d53d8,
               PlayerPointerAddress = 0x004894c8,
               //GameEndedAddress = 0x005d548c,
               MapListArrayAddress = 0x005281E8,
               CurrentMapIndexAddress = 0x005281F4,
               SealWinCounterAddress = 0x005d5914,
               TerroristWinCounterAddress = 0x005d5928,
               RoomNameAddress = 0x00662664,
               PlayerKillsOffset = 0x48C,
               PlayerDeathsOffset = 0x494,
               MapList = SocomIMapList,
               // SOCOM 1 has the player total in 1 address so I will just use sealPlayerCountAddress for this
               SealPlayerCountAddress = 0x0059C798,
               MaxPlayersAddress = 0x005d5888,
               GameLogo = Properties.Resources.s1_GameLogo
           },
           // SOCOM 1 Black Label Disk 10 & Greatest hits Disk 10 & 11
           new GameInformationModel()
           {
               GameHash = "610767D2D8D253C38CA2595F87E178C5",
               JoinedGameAddress = 0x0059ecc8,
               JoinedGameLateAddress= 0x005d53d8,
               PlayerPointerAddress = 0x004894c8,
               //GameEndedAddress = 0x005d548c,
               MapListArrayAddress = 0x005281E8,
               CurrentMapIndexAddress = 0x005281F4,
               SealWinCounterAddress = 0x005d5914,
               TerroristWinCounterAddress = 0x005d5928,
               RoomNameAddress = 0x00662664,
               PlayerKillsOffset = 0x48C,
               PlayerDeathsOffset = 0x494,
               MapList = SocomIMapList,
               // SOCOM 1 has the player total in 1 address so I will just use sealPlayerCountAddress for this
               SealPlayerCountAddress = 0x0059C798,
               MaxPlayersAddress = 0x005d5888,
               GameLogo = Properties.Resources.s1_GameLogo
           },
           //SOCOM 3
           new GameInformationModel()
           {
               GameHash = "2C7B35F81D54D3E45E072C1ACA6D759C",
               JoinedGameAddress = 0x007bcb34,
               JoinedGameLateAddress = 0x006d50a8,
               PlayerPointerAddress = 0x006723f8,
               // This is different from SOCOM 1 and 2 as it's not a list and just the Id of the current map. On CA this changes
               // to 0x04 at the end of game screen and once you go back to lobby it will update to the next one so I should
               // have an image or something showing this for that Id
               MapListArrayAddress = 0x00671fd8,
               SealWinCounterAddress = 0x000C283E4,
               TerroristWinCounterAddress = 0x000C283EC,
               // Room name is not a pointer in this case
               RoomNameAddress = 0x00B7AA64,
               PlayerKillsOffset = 0x6c4,
               PlayerDeathsOffset =0x6cc,
               SealPlayerCountAddress = 0x00697290,
               TerroristPlayerCountAddress = 0x00697298,
               MaxPlayersAddress = 0x00C28344,
               MapList = SOCOM3CAMapList,
               GameLogo = Properties.Resources.s3_GameLogo
           },
           //SOCOM CA
           new GameInformationModel()
           {
               GameHash = "7F509DFA68DAF0CC87C7096C24BC29E4",
               JoinedGameAddress = 0x0087a634,
               JoinedGameLateAddress = 0x00773828,
               // This doesn't necessarilu designate a late join but it's good enough for a check
               PlayerPointerAddress = 0x00709d98,
               //GameEndedAddress = 0x0,
               // This is different from SOCOM 1 and 2 as it's not a list and just the Id of the current map. On CA this changes
               // to 0x04 at the end of game screen and once you go back to lobby it will update to the next one so I should
               // have an image or something showing this for that Id
               MapListArrayAddress = 0x007098B8,
               SealWinCounterAddress = 0x00CCDDEC,
               TerroristWinCounterAddress = 0x00CCDDF4,
               // Room name is not a pointer in this case
               RoomNameAddress = 0x00C3D9CC,
               PlayerKillsOffset = 0x5C0,
               PlayerDeathsOffset = 0x5C8,
               MapList = SOCOM3CAMapList,
               // Joining a game late will not have values for the counts. Once you are loaded in they will update
               SealPlayerCountAddress = 0x0073f178,
               TerroristPlayerCountAddress = 0x0073f180,
               MaxPlayersAddress = 0x00CCDD4C,
               GameLogo = Properties.Resources.sca_GameLogo
           }
        };
    }
}
